#!/usr/bin/env ruby

# frozen_string_literal: true

SKIPPED = {}

def result_or_skipped(day:, part:)
  return "*** SKIPPED ***" if SKIPPED["#{day}.#{part}"]

  Kernel.const_get("Day#{day}").new.send("result#{part}")
end

puts
puts "Advent of Code 2023 — Ruby Edition"
puts "-" * 35

1.upto(24) do |day|
  padded_current_day = "Day%02d" % day
  current_day = "Day#{day}"
  break unless Dir.exist?(padded_current_day)

  Dir.chdir(padded_current_day) do
    require_relative padded_current_day + "/" + current_day

    print "Day #{day} — Result 1: "
    puts result_or_skipped(day:, part: 1)

    print "Day #{day} — Result 2: "
    puts result_or_skipped(day:, part: 2)
  end
end
